version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule: { interval: weekly }
    groups:
      codemirror: { patterns: ["@codemirror/*", "@lezer/*"] }
      tauri: { patterns: ["@tauri-apps/*"] }
    open-pull-requests-limit: 5
  - package-ecosystem: cargo
    directory: /src-tauri
    schedule: { interval: weekly }
    groups:
      tauri: { patterns: ["tauri*"] }
    open-pull-requests-limit: 5
  - package-ecosystem: github-actions
    directory: /
    schedule: { interval: monthly }
