// Regenerates src/brandIcons.ts from the Simple Icons package (CC0 SVG paths).
// Usage: npm i --no-save simple-icons && node dev/brand-icons.mjs
import { writeFileSync } from "node:fs";
import * as si from "simple-icons";

const pick = { postgres: "siPostgresql", mysql: "siMysql", mariadb: "siMariadb", sqlite: "siSqlite" };
let out = `// Official engine logos: SVG paths from Simple Icons (CC0, https://simpleicons.org).
// The logos remain trademarks of their owners and are used only to identify each engine.
// Generated by dev/brand-icons.mjs; do not edit by hand.

export const BRAND_PATHS: Record<string, { path: string; hex: string; title: string }> = {
`;
for (const [key, name] of Object.entries(pick)) {
  const icon = si[name];
  out += `  ${key}: { title: ${JSON.stringify(icon.title)}, hex: "#${icon.hex}", path: ${JSON.stringify(icon.path)} },\n`;
}
out += "};\n";
writeFileSync(new URL("../src/brandIcons.ts", import.meta.url), out);
console.log("wrote src/brandIcons.ts", out.length);
